"""Initial schema

Revision ID: 699640698467
Revises: 
Create Date: 2025-11-20 19:14:50.257027
"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

revision = '699640698467'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('children',
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender', native_enum=False, length=16), nullable=False),
    sa.Column('blood_type', sa.String(length=8), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_children_parent_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_children'))
    )
    op.create_index(op.f('ix_children_parent_id'), 'children', ['parent_id'], unique=False)
    op.create_table('growth_logs',
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_growth_logs_child_id_children'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_logs'))
    )
    op.create_index(op.f('ix_growth_logs_child_id'), 'growth_logs', ['child_id'], unique=False)
    op.create_table('medication_logs',
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=255), nullable=True),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_medication_logs_child_id_children'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_logs'))
    )
    op.create_index(op.f('ix_medication_logs_child_id'), 'medication_logs', ['child_id'], unique=False)
    op.create_table('vaccine_records',
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('vaccine_name', sa.String(length=255), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='vaccinestatus', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_vaccine_records_child_id_children'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vaccine_records'))
    )
    op.create_index(op.f('ix_vaccine_records_child_id'), 'vaccine_records', ['child_id'], unique=False)
    # op.drop_index(op.f('ix_transactions_customer_segment'), table_name='transactions')
    # op.drop_index(op.f('ix_transactions_product_category'), table_name='transactions')
    # op.drop_index(op.f('ix_transactions_product_id'), table_name='transactions')
    # op.drop_index(op.f('ix_transactions_region'), table_name='transactions')
    # op.drop_index(op.f('ix_transactions_sales_channel'), table_name='transactions')
    # op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    # op.drop_table('transactions')
    # op.drop_index(op.f('ix_products_category'), table_name='products')
    # op.drop_index(op.f('ix_products_product_id'), table_name='products')
    # op.drop_table('products')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('base_price', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('product_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('product_category', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('sales_channel', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('customer_segment', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', mysql.FLOAT(), nullable=False),
    sa.Column('discount_pct', mysql.FLOAT(), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('region', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('transactions_ibfk_1')),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_sales_channel'), 'transactions', ['sales_channel'], unique=False)
    op.create_index(op.f('ix_transactions_region'), 'transactions', ['region'], unique=False)
    op.create_index(op.f('ix_transactions_product_id'), 'transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_transactions_product_category'), 'transactions', ['product_category'], unique=False)
    op.create_index(op.f('ix_transactions_customer_segment'), 'transactions', ['customer_segment'], unique=False)
    # op.drop_index(op.f('ix_vaccine_records_child_id'), table_name='vaccine_records')
    # op.drop_table('vaccine_records')
    # op.drop_index(op.f('ix_medication_logs_child_id'), table_name='medication_logs')
    # op.drop_table('medication_logs')
    # op.drop_index(op.f('ix_growth_logs_child_id'), table_name='growth_logs')
    # op.drop_table('growth_logs')
    # op.drop_index(op.f('ix_children_parent_id'), table_name='children')
    # op.drop_table('children')
    # op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.drop_table('users')
    # ### end Alembic commands ###
